// <auto-generated />
using System;
using ClyvoVet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClyvoVet.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Animal", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<bool?>("Castrado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("castrado");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Especie")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("especie");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Raca")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("raca");

                    b.Property<string>("RacaId")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("raca_id");

                    b.Property<string>("Sexo")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("genero");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("tutor_id");

                    b.HasKey("Id");

                    b.HasIndex("RacaId");

                    b.HasIndex("TutorId");

                    b.ToTable("t_clyvo_animal", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.BaseDoenca", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<int>("Casos")
                        .HasColumnType("int")
                        .HasColumnName("casos");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("categoria");

                    b.Property<int>("Controles")
                        .HasColumnType("int")
                        .HasColumnName("controles");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CriadoEm"));

                    b.Property<string>("DoencaCodigo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("doenca_codigo");

                    b.Property<string>("DoencaNome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("doenca_nome");

                    b.Property<string>("Doi")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("doi");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("especie");

                    b.Property<string>("Fonte")
                        .HasColumnType("VARCHAR(300)")
                        .HasColumnName("fonte");

                    b.Property<string>("RacaChave")
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("raca_chave");

                    b.Property<string>("RacaTexto")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("raca_texto");

                    b.HasKey("Id");

                    b.ToTable("t_clyvo_base_doencas", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.EventoPet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("DATE")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("EspecieAlvo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("especie_alvo");

                    b.Property<string>("Estado")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("estado");

                    b.Property<bool>("Gratuito")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("gratuito");

                    b.Property<string>("LinkInscricao")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("link_inscricao");

                    b.Property<string>("Numero")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Organizador")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("organizador");

                    b.Property<string>("Rua")
                        .HasColumnType("VARCHAR(300)")
                        .HasColumnName("rua");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("t_clyvo_evento_pet", null, t =>
                        {
                            t.HasCheckConstraint("chk_evento_pet_ativo", "ativo IN (0,1)");

                            t.HasCheckConstraint("chk_evento_pet_gratuito", "gratuito IN (0,1)");
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Lembrete", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AgendadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("agendado_em");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("descricao");

                    b.Property<int?>("IntervaloDias")
                        .HasColumnType("int")
                        .HasColumnName("intervalo_dias");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("recorrente");

                    b.Property<DateTime?>("RepetirAte")
                        .HasColumnType("DATETIME")
                        .HasColumnName("repetir_ate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("idx_lembrete_animal");

                    b.HasIndex("Status", "AgendadoEm")
                        .HasDatabaseName("idx_lembrete_varredura");

                    b.ToTable("t_clyvo_lembrete", null, t =>
                        {
                            t.HasCheckConstraint("chk_lembrete_intervalo", "intervalo_dias IS NULL OR intervalo_dias > 0");

                            t.HasCheckConstraint("chk_lembrete_recorrente", "recorrente IN (0,1)");
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.ParecerIa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("animal_id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("gerado_em");

                    b.Property<string>("Modelo")
                        .HasColumnType("VARCHAR(120)")
                        .HasColumnName("modelo");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("origem");

                    b.Property<DateTime>("ValidoAte")
                        .HasColumnType("DATETIME")
                        .HasColumnName("valido_ate");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasDatabaseName("uk_parecer_ia_animal");

                    b.ToTable("t_clyvo_parecer_ia", null, t =>
                        {
                            t.HasCheckConstraint("ck_parecer_ia_origem", "origem IN ('IA','REGRAS')");
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.PredisposicaoSaude", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("criado_em");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CriadoEm"));

                    b.Property<string>("Doenca")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("doenca");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("especie");

                    b.Property<string>("FonteReferencia")
                        .HasColumnType("VARCHAR(300)")
                        .HasColumnName("fonte_referencia");

                    b.Property<decimal?>("IdadeMinimaAnos")
                        .HasColumnType("NUMERIC(4,1)")
                        .HasColumnName("idade_minima_anos");

                    b.Property<string>("Raca")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("raca");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("recomendacao");

                    b.HasKey("Id");

                    b.ToTable("t_clyvo_predisposicao_saude", (string)null);
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Produto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("EspecieIndicada")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("especie_indicada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("nome");

                    b.Property<string>("PorteIndicado")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("porte_indicado");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("NUMERIC(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.HasIndex("EspecieIndicada", "PorteIndicado")
                        .HasDatabaseName("idx_produto_especie_porte");

                    b.ToTable("t_clyvo_produto", null, t =>
                        {
                            t.HasCheckConstraint("chk_produto_ativo", "ativo IN (0,1)");

                            t.HasCheckConstraint("chk_produto_porte", "porte_indicado IN ('PEQUENO', 'MEDIO', 'GRANDE', 'TODOS')");
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Raca", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("chave");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("especie");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PorteTipico")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("porte_tipico");

                    b.HasKey("Id");

                    b.ToTable("t_clyvo_raca", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.SugestaoProduto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("animal_id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataSugestao")
                        .HasColumnType("DATE")
                        .HasColumnName("data_sugestao");

                    b.Property<string>("Justificativa")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("justificativa");

                    b.Property<string>("ProdutoId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("produto_id");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("idx_sugestao_animal");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("idx_sugestao_produto");

                    b.ToTable("t_clyvo_sugestao_produto", null, t =>
                        {
                            t.HasCheckConstraint("chk_sugestao_ativo", "ativo IN (0,1)");
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Tutor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasColumnType("VARCHAR(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("t_clyvo_tutor", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.TutorTelegram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("criado_em");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("tutor_id");

                    b.HasKey("Id");

                    b.HasIndex("TutorId")
                        .IsUnique()
                        .HasDatabaseName("uk_tutor_telegram_tutor");

                    b.ToTable("t_clyvo_tutor_telegram", (string)null);
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Animal", b =>
                {
                    b.HasOne("ClyvoVet.Domain.Entities.Raca", "RacaCatalogo")
                        .WithMany()
                        .HasForeignKey("RacaId")
                        .HasConstraintName("fk_animal_raca");

                    b.HasOne("ClyvoVet.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Animais")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animal_tutor");

                    b.Navigation("RacaCatalogo");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Lembrete", b =>
                {
                    b.HasOne("ClyvoVet.Domain.Entities.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lembrete_animal");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.ParecerIa", b =>
                {
                    b.HasOne("ClyvoVet.Domain.Entities.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parecer_ia_animal");
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.SugestaoProduto", b =>
                {
                    b.HasOne("ClyvoVet.Domain.Entities.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sugestao_animal");

                    b.HasOne("ClyvoVet.Domain.Entities.Produto", "Produto")
                        .WithMany("Sugestoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sugestao_produto");

                    b.Navigation("Animal");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Sugestoes");
                });

            modelBuilder.Entity("ClyvoVet.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
